<?php 

$queries = $this->getQueries();
$insertQueries = $this->getQueriesByType($block::QUERY_TYPE_INSERT);
$updateQueries = $this->getQueriesByType($block::QUERY_TYPE_UPDATE);
$readQueries = $this->getQueriesByType($block::QUERY_TYPE_SELECT);
$deleteQueries = $this->getQueriesByType($block::QUERY_TYPE_DELETE);
$transactions = $this->getQueriesByType($block::QUERY_TYPE_TRANSACTION);

$slowestQueries = $this->getSlowestQueries();

$totalNumberOfQueries = $this->getTotalNumberOfQueries();
$totalElapsedSecs = number_format($this->getTotalElapsedSecs(), 3);

?>

<?php if (count($queries)): ?>

<div class="mgt-developer-toolbar-sidebar-database-queries">
  <h2><?= __('Database Queries'); ?></h2>
  
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Time'); ?></th>
        <th><?= __('Count'); ?></th>
        <th><?= __('Read'); ?></th>
        <th><?= __('Insert'); ?></th>
        <th><?= __('Update'); ?></th>
        <th><?= __('Delete'); ?></th>
        <th><?= __('Transactions'); ?></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><?= $totalElapsedSecs; ?>s</td>
        <td><?= $totalNumberOfQueries; ?></td>
        <td><?= count($readQueries); ?></td>
        <td><?= count($insertQueries); ?></td>
        <td><?= count($updateQueries); ?></td>
        <td><?= count($deleteQueries); ?></td>
        <td><?= count($transactions); ?></td>
      </tr>
    </tbody>
  </table>
  
  <h3><?= __('Top 5 Slowest Queries'); ?></h3>
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Query'); ?></th>
        <th width="90px"><?= __('Time (ms)'); ?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($slowestQueries as $query): ?>
        <tr>
          <td>
            <details class="no-chevron line-clamp">
              <summary><code class="sql"><?= $query['query']; ?></code></summary>
          </td>
          <td>
            <?= number_format($query['time'], 5); ?>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>

  <?php $similarQueries = $block->getSimilarQueries() ?>
  <?php if ($similarQueries) : ?>
    <details class="no-chevron">
      <summary><h3><?= __('Similar Queries'); ?> - <?= count($similarQueries) ?></h3></summary>
      <table cellspacing="0" cellpadding="0" class="data-table">
        <thead>
          <tr>
            <th><?= __('Query'); ?></th>
            <th width="90px"><?= __('Sum (ms)'); ?></th>
            <th width="65px"><?= __('Count'); ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($similarQueries as $group): ?>
            <tr>
              <td>
                <details class="no-chevron">
                  <summary><code class="sql"><?= current($group['queries']) ?></code></summary>
                  <?php foreach ($group['queries'] as $i => $query): ?>
                    <?php if (!$i): continue; endif; ?>
                    <hr>
                    <code class="sql"><?= $query ?></code>
                  <?php endforeach ?>
                </details>
              </td>
              <td>
                <?= number_format($group['time'], 5); ?>
              </td>
              <td>
                <?= $group['count'] ?>
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </details>
  <?php endif ?>
  
  <h3><?= __('All Queries'); ?> - <?= $totalNumberOfQueries ?></h3>
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Query'); ?></th>
        <th width="90px"><?= __('Time (ms)'); ?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($queries as $query): ?>
        <tr>
          <td>
            <code class="sql"><?= $query['query']; ?></code>
          </td>
          <td>
            <?= number_format($query['time'], 5); ?>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>

<script>
  document.querySelectorAll('code.sql').forEach(el => {
    hljs.highlightElement(el);
  });
</script>

<?php endif ?>