<?php 

$queries = $this->getQueries();
$insertQueries = $this->getQueriesByType($block::QUERY_TYPE_INSERT);
$updateQueries = $this->getQueriesByType($block::QUERY_TYPE_UPDATE);
$readQueries = $this->getQueriesByType($block::QUERY_TYPE_SELECT);
$deleteQueries = $this->getQueriesByType($block::QUERY_TYPE_DELETE);
$transactions = $this->getQueriesByType($block::QUERY_TYPE_TRANSACTION);

$slowestQueries = $this->getSlowestQueries();

$totalNumberOfQueries = $this->getTotalNumberOfQueries();
$totalElapsedSecs = number_format($this->getTotalElapsedSecs(), 3);

?>

<?php if (count($queries)): ?>

<div class="mgt-developer-toolbar-sidebar-database-queries">
  <h2><?= __('Database Queries'); ?></h2>
  
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Time'); ?></th>
        <th><?= __('Count'); ?></th>
        <th><?= __('Read'); ?></th>
        <th><?= __('Insert'); ?></th>
        <th><?= __('Update'); ?></th>
        <th><?= __('Delete'); ?></th>
        <th><?= __('Transactions'); ?></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><?= $totalElapsedSecs; ?>s</td>
        <td><?= $totalNumberOfQueries; ?></td>
        <td><?= count($readQueries); ?></td>
        <td><?= count($insertQueries); ?></td>
        <td><?= count($updateQueries); ?></td>
        <td><?= count($deleteQueries); ?></td>
        <td><?= count($transactions); ?></td>
      </tr>
    </tbody>
  </table>
  
  <h3><?= __('Top 5 Slowest Queries'); ?></h3>
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Query'); ?></th>
        <th width="90px"><?= __('Time (ms)'); ?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($slowestQueries as $query): ?>
        <tr>
          <td>
            <div class="copy-wrapper">
              <details class="no-chevron line-clamp">
                <summary><code class="sql"><?= $query['query']; ?></code></summary>
              </details>
              <button class="copy">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" /><path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" /></svg>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" /><path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg>
              </button>
            </div>
          </td>
          <td>
            <?= number_format($query['time'], 5); ?>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>

  <?php $similarQueries = $block->getSimilarQueries() ?>
  <?php if ($similarQueries) : ?>
    <details class="no-chevron">
      <summary><h3><?= __('Similar Queries'); ?> - <?= count($similarQueries) ?></h3></summary>
      <table cellspacing="0" cellpadding="0" class="data-table">
        <thead>
          <tr>
            <th><?= __('Query'); ?></th>
            <th width="90px"><?= __('Sum (ms)'); ?></th>
            <th width="65px"><?= __('Count'); ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($similarQueries as $group): ?>
            <tr>
              <td>
                <details class="no-chevron">
                  <summary>
                    <div class="copy-wrapper">
                      <code class="sql"><?= current($group['queries']) ?></code>
                      <button class="copy">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" /><path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" /></svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" /><path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg>
                      </button>
                    </div>
                  </summary>
                  <?php foreach ($group['queries'] as $i => $query): ?>
                    <?php if (!$i): continue; endif; ?>
                    <hr>
                    <div class="copy-wrapper">
                      <code class="sql"><?= $query ?></code>
                      <button class="copy">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" /><path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" /></svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" /><path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg>
                      </button>
                    </div>
                  <?php endforeach ?>
                </details>
              </td>
              <td>
                <?= number_format($group['time'], 5); ?>
              </td>
              <td>
                <?= $group['count'] ?>
              </td>
            </tr>
          <?php endforeach ?>
        </tbody>
      </table>
    </details>
  <?php endif ?>
  
  <h3><?= __('All Queries'); ?> - <?= $totalNumberOfQueries ?></h3>
  <table cellspacing="0" cellpadding="0" class="data-table">
    <thead>
      <tr>
        <th><?= __('Query'); ?></th>
        <th width="90px"><?= __('Time (ms)'); ?></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($queries as $query): ?>
        <tr>
          <td>
            <div class="copy-wrapper">
              <code class="sql"><?= $query['query']; ?></code>
              <button class="copy">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" /><path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" /></svg>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" /><path fill-rule="evenodd" d="M4 5a2 2 0 012-2 3 3 0 003 3h2a3 3 0 003-3 2 2 0 012 2v11a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm9.707 5.707a1 1 0 00-1.414-1.414L9 12.586l-1.293-1.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" /></svg>
              </button>
            </div>
          </td>
          <td>
            <?= number_format($query['time'], 5); ?>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>

<script data-breeze>
  document.querySelectorAll('code.sql').forEach(el => {
    hljs.highlightElement(el);
  });

  require(['Mgt_DeveloperToolbar/js/clipboard'], function (Clipboard) {
    var clipboard = new (Clipboard || window.ClipboardJS)('.copy', {
      text: function (trigger) {
        return trigger.previousElementSibling.innerText;
      },
    });
    clipboard.on('success', function (e) {
      e.trigger.classList.add('copied');
      setTimeout(() => {
        e.trigger.classList.remove('copied');
      }, 2000);
    });
  });
</script>

<?php endif ?>